### ISSUE TITLE
Bug: INS tag not closed

### ISSUE THREAD

**Issue by Morziloeil** [caxy/php-htmldiff#64] opened 2017-09-08 14:07 UTC
Hi,

`$content = Caxy\HtmlDiff\HtmlDiff::create('<p>Lorem ipsum dolor sit amet</p>', '<p>Lorem ipsum dolor <strong>sit</strong> amet</p>')->build();
print_r(htmlentities($content));`

Result:

`<p>Lorem ipsum dolor <del class="diffmod">sit</del><strong class="diffmod"><ins class="mod"><ins class="diffmod">sit</ins></strong> amet</p>`

`<ins class="mod">` is not closed.

**Comment by jschroed91** [comment] 2017-09-12 02:07
Thanks for submitting this bug @Morziloeil - someone will have a look in the next couple of days

**Comment by SavageTiger** [comment] 2017-09-12 08:40
@jschroed91 Hi Josh, I gave it a quick look and there are a couple of things that i noticed.

First, to reproduce this you must have strong defined in SpecialCaseTags.
What i did in testHtmlDiff is <code>$diff = new HtmlDiff(trim($oldText), trim($newText), 'UTF-8', array('strong'));</code>

Second, the issue seems to be that the call <code>} elseif (array_search($words[ 0 ], $this->config->getSpecialCaseClosingTags()) !== false) {</code> inside insertTag is never properly evaluated. I try'd to fix it, but the code is not structured enough for me to make any sense of it. So maybe if someone looks at it that has a bit more experience with this class it might be fixed in no time.

Hop this helps.

**Comment by Julien1138** [comment] 2020-04-01 11:56
Hi. This bug still exists...

**Comment by jschroed91** [comment] 2020-04-01 15:05
Hi @Julien1138 - thank you for following up here. I'll look into this this week unless someone beats me to it and opens a PR

**Comment by SavageTiger** [comment] 2022-01-19 11:22
@Julien1138 This should be fixed in the latest version 0.1.14

**Closed** 2022-01-19 11:22 UTC
Labels: Bug
